#!/usr/bin/env bash

cat << EOF
_________            ______                 _________                ___       _________
______  /_____ _________  /__   ______      ______  /__________      __ |     / /__  __ \
___ _  /_  __ `/  ___/_  //_/   ___/ /_     ___ _  /_  __ \  _ \     __ | /| / /__  /_/ /
/ /_/ / / /_/ // /__ _  ,<      /_  __/     / /_/ / / /_/ /  __/     __ |/ |/ / _  ____/
\____/  \__,_/ \___/ /_/|_|      /_/        \____/  \____/\___/      ____/|__/  /_/

EOF

echo -e "\n--> Checking local dependencies"

# Check composer install
if [[ -z "$(which composer)" ]]
then
	echo -e "\n--> Can't find the composer command."
	echo -e "--> Make sure composer is installed correctly. "
	echo -e "--> https://getcomposer.org/"
	exit 1
else
	echo -e "\n--> Composer installed: OK"
	echo -e "    $(which composer)"
fi

# Ask & set project slug
while [ "$SLUG_OK" != "y" ]
do
	echo -e "\n--> Give a project slug"
	echo -e "    (keep it short and slug-like or slug_like)"
	read PROJECT_NAME

	PROJECT_SLUG=$(echo $PROJECT_NAME | tr '[:upper:]' '[:lower:]' | tr -d '[:space:][:punct:]')

	echo -e "\n--> We'll be using following settings:"
	echo -e "slug:      ${PROJECT_SLUG}"

	echo -e "\nOK? (y)es or (n)o"
	read SLUG_OK
done
